name: Python CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        set -euo pipefail
        python -m pip install --upgrade pip
        echo "Repository files at root:"
        ls -la

        if [ -f requirements.txt ]; then
          echo "Found requirements.txt, installing (CI mode)..."
          python -m pip install -r requirements.txt
        else
          echo "No requirements.txt found at repo root. Failing the job."
          ls -la
          exit 1
        fi

    - name: Run flake8
      run: |
        python -m pip install flake8
        # run flake8 but don't fail the job if there are style issues yet
        flake8 --max-line-length=100 src || true

    - name: Run tests
      run: |
        echo "No unit tests included yet. Add tests under tests/ to run them."
